In [1]:
import pandas as pd

### Due to limited computing, we divided the same data into 5 segments, and ran the labelling on the 5 datasets in parallel. Here we merge them and do further analysis

In [2]:
df_1 = pd.read_csv('randomsample_part1_with_predictions.csv')
df_2 = pd.read_csv('randomsample_part2_with_predictions.csv')
df_3 = pd.read_csv('randomsample_part3_with_predictions.csv')
df_4 = pd.read_csv('randomsample_part3_with_predictions.csv')
df_5 = pd.read_csv('randomsample_part5_with_predictions.csv')

In [3]:

merged = pd.concat([df_1, df_2, df_3, df_4, df_5], ignore_index=True)

cols_to_drop = ["sampled_vote", "predicted_vote", "vote_confidence", "vote_reasoning", "vote_thought"]
merged = merged.drop(columns=[c for c in cols_to_drop if c in merged.columns])

merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25025 entries, 0 to 25024
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           24165 non-null  float64
 1   constituency_name  25025 non-null  object
 2   gender             25025 non-null  object
 3   age_band           25025 non-null  object
 4   area_type          25025 non-null  object
 5   R                  25025 non-null  object
 6   G                  25025 non-null  object
 7   SG                 25025 non-null  object
 8   n_individuals      25025 non-null  int64
 9   stratum_share      24165 non-null  float64
 10  p_will_vote        24999 non-null  float64
 11  choice_thought     21457 non-null  object
 12  p_aitc             23626 non-null  float64
 13  p_nda              23604 non-null  float64
 14  p_lf               23602 non-null  float64
 15  p_inc              23619 non-null  float64
 16  p_nota             23592 non-null  float64
 17  persuadable        23195 non-null  object
 18  will_vote          0 non-null      float64
dtypes: float64(9), int64(1), object(9)
memory usage: 3.6+ MB

In [4]:
merged['p_will_vote'] = merged['p_will_vote'].apply(lambda x: x / 100 if x > 1 else x)

In [5]:
merged.head(5)

,eroll_no,constituency_name,gender,age_band,area_type,R,G,SG,n_individuals,stratum_share,p_will_vote,choice_thought,p_aitc,p_nda,p_lf,p_inc,p_nota,persuadable,will_vote
0,150.0,Jadavpur,Female,46-60,Urb,H,GEN,GUC,549,0.112224,0.83,"The user wants me to act as a 46-60 year old, ...",0.20,0.40,0.35,0.00,0.05,True,NaN
1,110.0,Dum Dum Uttar,Female,46-60,Urb,H,GEN,GUC,460,0.109290,0.71,The user wants me to act as a specific voter i...,0.15,0.75,0.05,0.04,0.01,False,NaN
2,114.0,Dum Dum,Female,46-60,Urb,H,GEN,GUC,417,0.101856,0.78,The user wants me to act as a specific voter f...,0.12,0.82,0.01,0.01,0.04,False,NaN
3,152.0,Tollyganj,Female,46-60,Urb,H,GEN,GUC,399,0.098689,0.75,1. **Deconstruct the Persona:**\n * **Na...,0.50,0.35,0.05,0.05,0.05,True,NaN
4,106.0,Jagatdal,Male,46-60,Urb,H,GEN,GUC,390,0.091228,0.81,NaN,0.50,0.40,0.00,0.05,0.05,True,NaN

In [6]:
print(merged['p_will_vote'].agg(['max', 'min', 'mean']))
print(f"Mode: {merged['p_will_vote'].mode()[0]}")

max     1.000000
min     0.000000
mean    0.819219
Name: p_will_vote, dtype: float64
Mode: 0.85

In [7]:
import numpy as np

merged['will_vote'] = merged['p_will_vote'].apply(
    lambda p: np.random.binomial(1, p) if pd.notna(p) else np.nan
)

In [8]:
merged['will_vote'].mean() * 100

np.float64(81.75927037081483)

In [9]:
merged[merged['constituency_name'].str.contains('Kolkata', case=False, na=False)]['will_vote'].mean() * 100

np.float64(60.78431372549019)

In [10]:
kolkata_constituencies = [
    'Kolkata Port', 'Bhabanipur', 'Rashbehari', 'Ballygunge',
    'Chowranghee', 'Entally', 'Beleghata', 'Jorasanko',
    'Shyampukur', 'Maniktola', 'Kashipur Belgachhia'
]

merged[merged['constituency_name'].isin(kolkata_constituencies)]['will_vote'].mean() * 100

np.float64(71.53179190751445)

In [11]:
merged.to_csv("merged_sample_v4.csv", index=False)

In [4]:
df_1 = pd.read_csv('randomsample_part1_with_predictions.csv')
df_2 = pd.read_csv('randomsample_part2_with_predictions.csv')
df_3 = pd.read_csv('randomsample_part3_with_predictions.csv')
df_4 = pd.read_csv('randomsample_part3_with_predictions.csv')
df_5 = pd.read_csv('randomsample_part5_with_predictions.csv')
df_6 = pd.read_csv('randomsample_part6_with_predictions.csv')
df_7 = pd.read_csv('randomsample_part7_with_predictions.csv')
df_8 = pd.read_csv('randomsample_part8_with_predictions.csv')
df_9 = pd.read_csv('randomsample_part9_with_predictions.csv')

In [5]:
df_1.head()
df_2.head()
df_3.head()
df_4.head()

,eroll_no,constituency_name,gender,age_band,area_type,R,G,SG,n_individuals,stratum_share,...,sampled_vote,predicted_vote,vote_confidence,vote_reasoning,vote_thought,p_aitc,p_nda,p_lf,p_inc,p_nota
0,156.0,Budge Budge,Male,26-35,Urb,M,OBC,BM,110,0.029714,...,NOTA,AITC+,High,Fear of BJP and CAA/NRC is paramount for my Mu...,NaN,0.85,0.00,0.00,0.00,0.15
1,156.0,Budge Budge,Male,36-45,Rur,M,GEN,BM,16,0.004322,...,AITC+,AITC+,Medium,Overwhelming fear of BJP and CAA outweighs ang...,NaN,0.75,0.00,0.02,0.05,0.18
2,156.0,Budge Budge,Male,36-45,Rur,M,OBC,BM,14,0.003782,...,AITC+,AITC+,High,The overwhelming fear of BJP's CAA/NRC policie...,NaN,0.88,0.10,0.01,0.01,0.00
3,156.0,Budge Budge,Male,36-45,Urb,H,GEN,GUC,69,0.018639,...,NDA,AITC+,Medium,The massive Lok Sabha victory for AITC in this...,NaN,0.70,0.28,0.01,0.01,0.00
4,156.0,Budge Budge,Male,36-45,Urb,H,GEN,MAT,4,0.001080,...,LF+,AITC+,Medium,The community's decisive 2024 Lok Sabha vote f...,NaN,0.75,0.20,0.04,0.01,0.00

In [6]:
df_1.info()
df_2.info()
df_3.info()
df_4.info()
df_5.info()
df_6.info()
df_7.info()
df_8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4810 entries, 0 to 4809
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           4810 non-null   float64
 1   constituency_name  4810 non-null   object
 2   gender             4810 non-null   object
 3   age_band           4810 non-null   object
 4   area_type          4810 non-null   object
 5   R                  4810 non-null   object
 6   G                  4810 non-null   object
 7   SG                 4810 non-null   object
 8   n_individuals      4810 non-null   int64
 9   stratum_share      4810 non-null   float64
 10  dup_count          4810 non-null   int64
 11  will_vote          4780 non-null   object
 12  sampled_vote       4810 non-null   object
 13  predicted_vote     4780 non-null   object
 14  vote_confidence    4779 non-null   object
 15  vote_reasoning     4780 non-null   object
 16  vote_thought       0 non-null      float64
 17  p_aitc             4780 non-null   float64
 18  p_nda              4780 non-null   float64
 19  p_lf               4780 non-null   float64
 20  p_inc              4780 non-null   float64
 21  p_nota             4777 non-null   float64
dtypes: float64(8), int64(2), object(12)
memory usage: 826.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4810 entries, 0 to 4809
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           4810 non-null   float64
 1   constituency_name  4810 non-null   object
 2   gender             4810 non-null   object
 3   age_band           4810 non-null   object
 4   area_type          4810 non-null   object
 5   R                  4810 non-null   object
 6   G                  4810 non-null   object
 7   SG                 4810 non-null   object
 8   n_individuals      4810 non-null   int64
 9   stratum_share      4810 non-null   float64
 10  dup_count          4810 non-null   int64
 11  will_vote          4784 non-null   object
 12  sampled_vote       4810 non-null   object
 13  predicted_vote     4784 non-null   object
 14  vote_confidence    4784 non-null   object
 15  vote_reasoning     4784 non-null   object
 16  vote_thought       0 non-null      float64
 17  p_aitc             4784 non-null   float64
 18  p_nda              4783 non-null   float64
 19  p_lf               4783 non-null   float64
 20  p_inc              4784 non-null   float64
 21  p_nota             4779 non-null   float64
dtypes: float64(8), int64(2), object(12)
memory usage: 826.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4810 entries, 0 to 4809
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           4810 non-null   float64
 1   constituency_name  4810 non-null   object
 2   gender             4810 non-null   object
 3   age_band           4810 non-null   object
 4   area_type          4810 non-null   object
 5   R                  4810 non-null   object
 6   G                  4810 non-null   object
 7   SG                 4810 non-null   object
 8   n_individuals      4810 non-null   int64
 9   stratum_share      4810 non-null   float64
 10  dup_count          4810 non-null   int64
 11  will_vote          4781 non-null   object
 12  sampled_vote       4810 non-null   object
 13  predicted_vote     4780 non-null   object
 14  vote_confidence    4779 non-null   object
 15  vote_reasoning     4780 non-null   object
 16  vote_thought       0 non-null      float64
 17  p_aitc             4780 non-null   float64
 18  p_nda              4781 non-null   float64
 19  p_lf               4780 non-null   float64
 20  p_inc              4780 non-null   float64
 21  p_nota             4775 non-null   float64
dtypes: float64(8), int64(2), object(12)
memory usage: 826.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4810 entries, 0 to 4809
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           4810 non-null   float64
 1   constituency_name  4810 non-null   object
 2   gender             4810 non-null   object
 3   age_band           4810 non-null   object
 4   area_type          4810 non-null   object
 5   R                  4810 non-null   object
 6   G                  4810 non-null   object
 7   SG                 4810 non-null   object
 8   n_individuals      4810 non-null   int64
 9   stratum_share      4810 non-null   float64
 10  dup_count          4810 non-null   int64
 11  will_vote          4781 non-null   object
 12  sampled_vote       4810 non-null   object
 13  predicted_vote     4780 non-null   object
 14  vote_confidence    4779 non-null   object
 15  vote_reasoning     4780 non-null   object
 16  vote_thought       0 non-null      float64
 17  p_aitc             4780 non-null   float64
 18  p_nda              4781 non-null   float64
 19  p_lf               4780 non-null   float64
 20  p_inc              4780 non-null   float64
 21  p_nota             4775 non-null   float64
dtypes: float64(8), int64(2), object(12)
memory usage: 826.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1081 entries, 0 to 1080
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           1081 non-null   float64
 1   constituency_name  1081 non-null   object
 2   gender             1081 non-null   object
 3   age_band           1081 non-null   object
 4   area_type          1081 non-null   object
 5   R                  1081 non-null   object
 6   G                  1081 non-null   object
 7   SG                 1081 non-null   object
 8   n_individuals      1081 non-null   int64
 9   stratum_share      1081 non-null   float64
 10  dup_count          1081 non-null   int64
 11  will_vote          1063 non-null   object
 12  sampled_vote       1081 non-null   object
 13  predicted_vote     1063 non-null   object
 14  vote_confidence    1063 non-null   object
 15  vote_reasoning     1063 non-null   object
 16  vote_thought       0 non-null      float64
 17  p_aitc             1062 non-null   float64
 18  p_nda              1061 non-null   float64
 19  p_lf               1063 non-null   float64
 20  p_inc              1063 non-null   float64
 21  p_nota             1059 non-null   float64
dtypes: float64(8), int64(2), object(12)
memory usage: 185.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           1080 non-null   float64
 1   constituency_name  1080 non-null   object
 2   gender             1080 non-null   object
 3   age_band           1080 non-null   object
 4   area_type          1080 non-null   object
 5   R                  1080 non-null   object
 6   G                  1080 non-null   object
 7   SG                 1080 non-null   object
 8   n_individuals      1080 non-null   int64
 9   stratum_share      1080 non-null   float64
 10  dup_count          1080 non-null   int64
 11  will_vote          1056 non-null   object
 12  sampled_vote       1080 non-null   object
 13  predicted_vote     1056 non-null   object
 14  vote_confidence    1056 non-null   object
 15  vote_reasoning     1056 non-null   object
 16  vote_thought       0 non-null      float64
 17  p_aitc             1056 non-null   float64
 18  p_nda              1056 non-null   float64
 19  p_lf               1056 non-null   float64
 20  p_inc              1056 non-null   float64
 21  p_nota             1055 non-null   float64
dtypes: float64(8), int64(2), object(12)
memory usage: 185.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           1080 non-null   float64
 1   constituency_name  1080 non-null   object
 2   gender             1080 non-null   object
 3   age_band           1080 non-null   object
 4   area_type          1080 non-null   object
 5   R                  1080 non-null   object
 6   G                  1080 non-null   object
 7   SG                 1080 non-null   object
 8   n_individuals      1080 non-null   int64
 9   stratum_share      1080 non-null   float64
 10  dup_count          1080 non-null   int64
 11  will_vote          184 non-null    object
 12  sampled_vote       1080 non-null   object
 13  predicted_vote     184 non-null    object
 14  vote_confidence    184 non-null    object
 15  vote_reasoning     184 non-null    object
 16  vote_thought       0 non-null      float64
 17  p_aitc             184 non-null    float64
 18  p_nda              183 non-null    float64
 19  p_lf               184 non-null    float64
 20  p_inc              184 non-null    float64
 21  p_nota             184 non-null    float64
dtypes: float64(8), int64(2), object(12)
memory usage: 185.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           1080 non-null   float64
 1   constituency_name  1080 non-null   object
 2   gender             1080 non-null   object
 3   age_band           1080 non-null   object
 4   area_type          1080 non-null   object
 5   R                  1080 non-null   object
 6   G                  1080 non-null   object
 7   SG                 1080 non-null   object
 8   n_individuals      1080 non-null   int64
 9   stratum_share      1080 non-null   float64
 10  dup_count          1080 non-null   int64
 11  will_vote          1061 non-null   object
 12  sampled_vote       1080 non-null   object
 13  predicted_vote     1061 non-null   object
 14  vote_confidence    1061 non-null   object
 15  vote_reasoning     1061 non-null   object
 16  vote_thought       0 non-null      float64
 17  p_aitc             1061 non-null   float64
 18  p_nda              1061 non-null   float64
 19  p_lf               1061 non-null   float64
 20  p_inc              1061 non-null   float64
 21  p_nota             1059 non-null   float64
dtypes: float64(8), int64(2), object(12)
memory usage: 185.8+ KB

In [7]:

merged = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9], ignore_index=True)

cols_to_drop = ["sampled_vote", "predicted_vote", "vote_confidence", "vote_reasoning", "vote_thought"]
merged = merged.drop(columns=[c for c in cols_to_drop if c in merged.columns])

merged.to_csv("merged_sample_v1.csv", index=False)

In [12]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           14499 non-null  float64
 1   constituency_name  15000 non-null  object
 2   gender             15000 non-null  object
 3   age_band           15000 non-null  object
 4   area_type          15000 non-null  object
 5   R                  15000 non-null  object
 6   G                  15000 non-null  object
 7   SG                 15000 non-null  object
 8   n_individuals      15000 non-null  int64
 9   stratum_share      14499 non-null  float64
 10  p_will_vote        14984 non-null  float64
 11  choice_thought     14197 non-null  object
 12  p_aitc             14234 non-null  float64
 13  p_nda              14232 non-null  float64
 14  p_lf               14234 non-null  float64
 15  p_inc              14234 non-null  float64
 16  p_nota             14227 non-null  float64
 17  persuadable        14169 non-null  object
 18  will_vote          0 non-null      float64
 19  is_voter           14984 non-null  float64
dtypes: float64(10), int64(1), object(9)
memory usage: 2.3+ MB

In [9]:
merged = merged.loc[merged.index.repeat(merged['dup_count'])].reset_index(drop=True)

In [13]:
merged['constituency_name'].nunique()

294

In [12]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58030 entries, 0 to 58029
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eroll_no           58030 non-null  float64
 1   constituency_name  58030 non-null  object
 2   gender             58030 non-null  object
 3   age_band           58030 non-null  object
 4   area_type          58030 non-null  object
 5   R                  58030 non-null  object
 6   G                  58030 non-null  object
 7   SG                 58030 non-null  object
 8   n_individuals      58030 non-null  int64
 9   stratum_share      58030 non-null  float64
 10  dup_count          58030 non-null  int64
 11  will_vote          55628 non-null  object
 12  p_aitc             55609 non-null  float64
 13  p_nda              55621 non-null  float64
 14  p_lf               55621 non-null  float64
 15  p_inc              55624 non-null  float64
 16  p_nota             55583 non-null  float64
dtypes: float64(7), int64(2), object(8)
memory usage: 7.5+ MB

In [13]:
merged.to_csv("merged_sample_v4.csv", index=False)

In [15]:
merged = pd.read_csv("merged_sample_v3.csv")

# Check if probabilities sum to 1
prob_cols = ["p_aitc", "p_nda", "p_lf", "p_inc", "p_nota"]
merged["prob_sum"] = merged[prob_cols].sum(axis=1)
print("Probability sum stats:")
print(merged["prob_sum"].describe())
print("\nRows where sum > 1.05:", (merged["prob_sum"] > 1.05).sum())
print("Rows where sum < 0.95:", (merged["prob_sum"] < 0.95).sum())

Probability sum stats:
count    15000.000000
mean         0.955337
std          0.838275
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        100.000000
Name: prob_sum, dtype: float64

Rows where sum > 1.05: 8
Rows where sum < 0.95: 785

In [12]:
sf = pd.read_csv("stratification_frame_cleaned.csv")

In [13]:
# ── The 17 constituencies missing from survey ──────────────────────────────────
missing_17 = [
    'Behala Paschim', 'Behala Purba', 'Beleghata', 'Bidhannagar',
    'Darjeeling', 'Entally', 'Jorasanko', 'Kalimpong', 'Kasba',
    'Kashipur Belgachhia', 'Kharagpur Sadar', 'Kurseong', 'Maniktola',
    'Metiaburuz', 'Rajarhat New Town', 'Rashbehari', 'Shyampukur'
]

sf_missing = sf[sf["constituency_name"].isin(missing_17)]

print("Rows in SF for missing 17 constituencies:", len(sf_missing))
print("Constituencies found:", sf_missing["constituency_name"].nunique())
print("Which ones:", sorted(sf_missing["constituency_name"].unique()))

print("\nn_individuals per constituency:")
print(sf_missing.groupby("constituency_name")["n_individuals"].agg(
    rows="count",
    total_voters="sum",
    mean_stratum="mean"
).sort_values("total_voters", ascending=False))

print("\nGender distribution:")
print(sf_missing["gender"].value_counts())

print("\nReligion distribution:")
print(sf_missing["R"].value_counts())

print("\nCaste distribution:")
print(sf_missing["G"].value_counts())

print("\nMissing values in these rows:")
print(sf_missing.isnull().sum())

Rows in SF for missing 17 constituencies: 3753
Constituencies found: 17
Which ones: ['Behala Paschim', 'Behala Purba', 'Beleghata', 'Bidhannagar', 'Darjeeling', 'Entally', 'Jorasanko', 'Kalimpong', 'Kasba', 'Kashipur Belgachhia', 'Kharagpur Sadar', 'Kurseong', 'Maniktola', 'Metiaburuz', 'Rajarhat New Town', 'Rashbehari', 'Shyampukur']

n_individuals per constituency:
                     rows  total_voters  mean_stratum
constituency_name
Darjeeling            362          1913      5.284530
Rajarhat New Town     215          1827      8.497674
Behala Paschim        220          1798      8.172727
Kurseong              354          1755      4.957627
Kasba                 194          1666      8.587629
Behala Purba          220          1665      7.568182
Kalimpong             327          1629      4.981651
Kashipur Belgachhia   197          1509      7.659898
Beleghata             197          1506      7.644670
Bidhannagar           182          1378      7.571429
Maniktola             194          1374      7.082474
Kharagpur Sadar       209          1275      6.100478
Entally               211          1231      5.834123
Metiaburuz            166          1165      7.018072
Shyampukur            182          1071      5.884615
Rashbehari            163          1050      6.441718
Jorasanko             160           843      5.268750

Gender distribution:
gender
Male          1712
Female        1185
Plus            69
Khi             61
Sly             53
              ...
Same             1
Shri             1
Single           1
TQG1575497       1
Meie             1
Name: count, Length: 108, dtype: int64

Religion distribution:
R
H    2807
M     669
O     277
Name: count, dtype: int64

Caste distribution:
G
GEN    1446
OBC    1162
ST      578
SC      551
O        16
Name: count, dtype: int64

Missing values in these rows:
eroll_no             3753
constituency_name       0
gender                  0
age_band                0
area_type               0
R                       0
G                       0
SG                      0
n_individuals           0
stratum_share        3753
dtype: int64

In [16]:
print("Breakdown of rows < 0.95:")
low_sum = merged[merged["prob_sum"] < 0.95]
print(low_sum["will_vote"].value_counts(dropna=False))
print(f"\nTotal non-voters: {(merged['will_vote'] != True).sum()}")
print(f"Rows < 0.95: {(merged['prob_sum'] < 0.95).sum()}")

Breakdown of rows < 0.95:
will_vote
NaN    785
Name: count, dtype: int64

Total non-voters: 15000
Rows < 0.95: 785

In [17]:
merged = merged[merged["will_vote"].notna()].copy()

print(f"Rows after dropping NaN will_vote: {len(merged)}")
print(f"will_vote distribution:")
print(merged["will_vote"].value_counts(dropna=False))

merged.to_csv("merged_sample_v1.csv", index=False)
print("\nSaved.")

Rows after dropping NaN will_vote: 0
will_vote distribution:
Series([], Name: count, dtype: int64)

Saved.

In [18]:
prob_cols = ["p_aitc", "p_nda", "p_lf", "p_inc", "p_nota"]

# Step 1: identify and fix rows where values look like percentages (sum ~100)
pct_rows = merged["prob_sum"] > 5
print(f"Rows that look like percentages (sum > 5): {pct_rows.sum()}")
merged.loc[pct_rows, prob_cols] = merged.loc[pct_rows, prob_cols] / 100

# Recompute sum
merged["prob_sum"] = merged[prob_cols].sum(axis=1)

# Step 2: normalise all rows where will_vote==True and sum > 0
voters_mask = (merged["will_vote"] == True) & (merged["prob_sum"] > 0)
merged.loc[voters_mask, prob_cols] = (
    merged.loc[voters_mask, prob_cols]
    .div(merged.loc[voters_mask, "prob_sum"], axis=0)
)

# Step 3: set all probs to 0 for non-voters
non_voters_mask = merged["will_vote"] != True
merged.loc[non_voters_mask, prob_cols] = 0.0

# Step 4: verify
merged["prob_sum"] = merged[prob_cols].sum(axis=1)
print("\nAfter fix — probability sum stats (voters only):")
print(merged.loc[voters_mask, "prob_sum"].describe())
print(f"\nRows > 1.05: {(merged['prob_sum'] > 1.05).sum()}")
print(f"Rows < 0.95 (voters only): {(merged.loc[voters_mask, 'prob_sum'] < 0.95).sum()}")

# Step 5: save
merged.to_csv("merged_sample_v1.csv", index=False)
print("\nSaved merged_sample_v1.csv")

Rows that look like percentages (sum > 5): 0

After fix — probability sum stats (voters only):
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: prob_sum, dtype: float64

Rows > 1.05: 0
Rows < 0.95 (voters only): 0

Saved merged_sample_v1.csv

In [15]:
merged.head()

,eroll_no,constituency_name,gender,age_band,area_type,R,G,SG,n_individuals,stratum_share,dup_count,will_vote,p_aitc,p_nda,p_lf,p_inc,p_nota
0,1.0,Mekliganj,Female,18-25,Rur,H,GEN,GUC,103,0.029437,6,True,0.48,0.49,0.0,0.0,0.03
1,1.0,Mekliganj,Female,18-25,Rur,H,GEN,GUC,103,0.029437,6,True,0.48,0.49,0.0,0.0,0.03
2,1.0,Mekliganj,Female,18-25,Rur,H,GEN,GUC,103,0.029437,6,True,0.48,0.49,0.0,0.0,0.03
3,1.0,Mekliganj,Female,18-25,Rur,H,GEN,GUC,103,0.029437,6,True,0.48,0.49,0.0,0.0,0.03
4,1.0,Mekliganj,Female,18-25,Rur,H,GEN,GUC,103,0.029437,6,True,0.48,0.49,0.0,0.0,0.03

In [16]:
import pandas as pd
sf = pd.read_csv("stratification_frame.csv")
sf.head()

/var/folders/vn/5dcbgwv57qz4cnnv8pj5rykr0000gn/T/ipykernel_74861/2171664849.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  sf = pd.read_csv("stratification_frame.csv")

,eroll_no,constituency_name,gender,age_band,area_type,R,G,SG,n_individuals,stratum_share
0,1.0,Mekliganj,Female,26-35,Rur,H,GEN,GUC,283,0.080880
1,1.0,Mekliganj,Male,36-45,Rur,H,GEN,GUC,274,0.078308
2,1.0,Mekliganj,Male,26-35,Rur,H,GEN,GUC,272,0.077736
3,1.0,Mekliganj,Female,36-45,Rur,H,GEN,GUC,244,0.069734
4,1.0,Mekliganj,Male,46-60,Rur,H,GEN,GUC,213,0.060875

In [17]:
# ── Basic structure ────────────────────────────────────────────────────────────
print("Shape:", sf.shape)
print("\nColumns:", sf.columns.tolist())
print("\nDtypes:\n", sf.dtypes)
print("\nHead:\n", sf.head())

# ── Missing values ─────────────────────────────────────────────────────────────
print("\nMissing values:\n", sf.isnull().sum())

# ── Key column distributions ───────────────────────────────────────────────────
for col in ["gender", "age_band", "area_type", "R", "G", "SG"]:
    print(f"\n--- {col} ---")
    print(sf[col].value_counts(dropna=False))

# ── Constituency coverage ──────────────────────────────────────────────────────
print("\nUnique constituencies:", sf["constituency_name"].nunique())
print("First 20:", sorted(sf["constituency_name"].dropna().unique())[:20])

# ── n_individuals summary ──────────────────────────────────────────────────────
print("\nn_individuals summary:\n", sf["n_individuals"].describe())
print("Total individuals in SF:", sf["n_individuals"].sum())

# ── Rows per constituency ──────────────────────────────────────────────────────
rows_per_const = sf.groupby("constituency_name").size().describe()
print("\nRows per constituency:\n", rows_per_const)

Shape: (66670, 10)

Columns: ['eroll_no', 'constituency_name', 'gender', 'age_band', 'area_type', 'R', 'G', 'SG', 'n_individuals', 'stratum_share']

Dtypes:
 eroll_no             float64
constituency_name     object
gender                object
age_band              object
area_type             object
R                     object
G                     object
SG                    object
n_individuals          int64
stratum_share        float64
dtype: object

Head:
    eroll_no constituency_name  gender age_band area_type  R    G   SG  \
0       1.0         Mekliganj  Female    26-35       Rur  H  GEN  GUC
1       1.0         Mekliganj    Male    36-45       Rur  H  GEN  GUC
2       1.0         Mekliganj    Male    26-35       Rur  H  GEN  GUC
3       1.0         Mekliganj  Female    36-45       Rur  H  GEN  GUC
4       1.0         Mekliganj    Male    46-60       Rur  H  GEN  GUC

   n_individuals  stratum_share
0            283       0.080880
1            274       0.078308
2            272       0.077736
3            244       0.069734
4            213       0.060875

Missing values:
 eroll_no             5122
constituency_name       0
gender                  0
age_band                0
area_type            5360
R                       0
G                       0
SG                      0
n_individuals           0
stratum_share        5122
dtype: int64

--- gender ---
gender
Male       32471
Female     32326
Maie         181
Main         155
Mae          146
           ...
28             1
43             1
56             1
Old            1
Fermain        1
Name: count, Length: 210, dtype: int64

--- age_band ---
age_band
46-60    14703
36-45    14421
26-35    14380
60+      12337
18-25    10829
Name: count, dtype: int64

--- area_type ---
area_type
Rur    37313
Urb    23997
NaN     5360
Name: count, dtype: int64

--- R ---
R
H    49541
M    14070
O     3059
Name: count, dtype: int64

--- G ---
G
OBC    22845
GEN    19211
SC     15842
ST      8443
O        329
Name: count, dtype: int64

--- SG ---
SG
MAT      12887
BM       12257
O        12232
GUC       7149
MAH       6507
RAJ       6188
SAN       4468
NAM       2584
UM        1710
OBC_H      646
TEA         42
Name: count, dtype: int64

Unique constituencies: 294
First 20: ['Alipurduars', 'Amdanga', 'Amta', 'Arambag', 'Asansol Dakshin', 'Asansol Uttar', 'Ashoknagar', 'Ausgram', 'Baduria', 'Bagda', 'Baghmundi', 'Bagnan', 'Baharampur', 'Baisnabnagar', 'Balagarh', 'Balarampur (Purulia)', 'Bally', 'Ballygunge', 'Balurghat', 'Bandwan']

n_individuals summary:
 count    66670.000000
mean        14.358842
std         29.984965
min          1.000000
25%          1.000000
50%          3.000000
75%         13.000000
max        549.000000
Name: n_individuals, dtype: float64
Total individuals in SF: 957304

Rows per constituency:
 count    294.000000
mean     226.768707
std       52.074647
min      126.000000
25%      187.000000
50%      222.000000
75%      262.000000
max      367.000000
dtype: float64

In [18]:
# ── The 17 constituencies missing from survey ──────────────────────────────────
missing_17 = [
    'Behala Paschim', 'Behala Purba', 'Beleghata', 'Bidhannagar',
    'Darjeeling', 'Entally', 'Jorasanko', 'Kalimpong', 'Kasba',
    'Kashipur Belgachhia', 'Kharagpur Sadar', 'Kurseong', 'Maniktola',
    'Metiaburuz', 'Rajarhat New Town', 'Rashbehari', 'Shyampukur'
]

sf_missing = sf[sf["constituency_name"].isin(missing_17)]

print("Rows in SF for missing 17 constituencies:", len(sf_missing))
print("Constituencies found:", sf_missing["constituency_name"].nunique())
print("Which ones:", sorted(sf_missing["constituency_name"].unique()))

print("\nn_individuals per constituency:")
print(sf_missing.groupby("constituency_name")["n_individuals"].agg(
    rows="count",
    total_voters="sum",
    mean_stratum="mean"
).sort_values("total_voters", ascending=False))

print("\nGender distribution:")
print(sf_missing["gender"].value_counts())

print("\nReligion distribution:")
print(sf_missing["R"].value_counts())

print("\nCaste distribution:")
print(sf_missing["G"].value_counts())

print("\nMissing values in these rows:")
print(sf_missing.isnull().sum())

Rows in SF for missing 17 constituencies: 3753
Constituencies found: 17
Which ones: ['Behala Paschim', 'Behala Purba', 'Beleghata', 'Bidhannagar', 'Darjeeling', 'Entally', 'Jorasanko', 'Kalimpong', 'Kasba', 'Kashipur Belgachhia', 'Kharagpur Sadar', 'Kurseong', 'Maniktola', 'Metiaburuz', 'Rajarhat New Town', 'Rashbehari', 'Shyampukur']

n_individuals per constituency:
                     rows  total_voters  mean_stratum
constituency_name
Darjeeling            362          1913      5.284530
Rajarhat New Town     215          1827      8.497674
Behala Paschim        220          1798      8.172727
Kurseong              354          1755      4.957627
Kasba                 194          1666      8.587629
Behala Purba          220          1665      7.568182
Kalimpong             327          1629      4.981651
Kashipur Belgachhia   197          1509      7.659898
Beleghata             197          1506      7.644670
Bidhannagar           182          1378      7.571429
Maniktola             194          1374      7.082474
Kharagpur Sadar       209          1275      6.100478
Entally               211          1231      5.834123
Metiaburuz            166          1165      7.018072
Shyampukur            182          1071      5.884615
Rashbehari            163          1050      6.441718
Jorasanko             160           843      5.268750

Gender distribution:
gender
Female        1183
Male          1166
Maie           144
Main           132
Mae            126
              ...
Shri             1
Single           1
TQG1575497       1
Thirty           1
Fermain          1
Name: count, Length: 116, dtype: int64

Religion distribution:
R
H    2807
M     669
O     277
Name: count, dtype: int64

Caste distribution:
G
GEN    1446
OBC    1162
ST      578
SC      551
O        16
Name: count, dtype: int64

Missing values in these rows:
eroll_no             3753
constituency_name       0
gender                  0
age_band                0
area_type            3753
R                       0
G                       0
SG                      0
n_individuals           0
stratum_share        3753
dtype: int64

In [21]:
# ── Fix gender typos ───────────────────────────────────────────────────────────
print("Before fix - unique gender values:")
print(sf["gender"].value_counts(dropna=False).head(20))

# Map anything that looks like Male/Female to the correct value
import re

def clean_gender(val):
    if pd.isna(val):
        return val
    v = str(val).strip().lower()
    if v in ["male", "maie", "main", "mae", "mal", "mael", "mlae", "m", "mare", "mole", "Mais"]:
        return "Male"
    if v in ["female", "fermain", "femal", "famale", "femle", "feamle", "f", "fe"]:
        return "Female"
    return val   # keep original if unrecognised — inspect manually

sf["gender"] = sf["gender"].apply(clean_gender)

print("\nAfter fix:")
print(sf["gender"].value_counts(dropna=False))

# ── Check what's still unrecognised ───────────────────────────────────────────
unrecognised = sf[~sf["gender"].isin(["Male", "Female", None])]
print(f"\nStill unrecognised: {len(unrecognised)} rows")
if len(unrecognised) > 0:
    print(unrecognised["gender"].value_counts())

Before fix - unique gender values:
gender
Male       33125
Female     32327
Plus          79
Khi           61
Sly           53
Gender:       52
Mais          45
Sweet         43
Mother        43
Mate          42
B             39
Swiss         38
:             37
Swi           35
Maile         34
Fernale       33
V             32
Khee          20
Swee          20
Maje          16
Name: count, dtype: int64

After fix:
gender
Male      33125
Female    32328
Plus         79
Khi          61
Sly          53
          ...
6             1
32            1
25            1
47            1
Meie          1
Name: count, Length: 202, dtype: int64

Still unrecognised: 1217 rows
gender
Plus       79
Khi        61
Sly        53
Gender:    52
Mais       45
           ..
32          1
6           1
O           1
28          1
Meie        1
Name: count, Length: 200, dtype: int64

In [22]:
# ── Impute area_type NaN with constituency mode ────────────────────────────────
print("Before imputation:")
print(f"  NaN area_type: {sf['area_type'].isna().sum()}")
print(f"  Constituencies with NaN: {sf[sf['area_type'].isna()]['constituency_name'].nunique()}")

# Impute with constituency mode
sf["area_type"] = sf.groupby("constituency_name")["area_type"].transform(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else "Rur")
)

print("\nAfter imputation:")
print(sf["area_type"].value_counts(dropna=False))
print(f"  Remaining NaN: {sf['area_type'].isna().sum()}")

# ── Safety check — if any constituency had ALL NaN area_type ──────────────────
# (mode would fail — fallback to state-wide mode)
if sf["area_type"].isna().sum() > 0:
    state_mode = sf["area_type"].mode()[0]
    sf["area_type"] = sf["area_type"].fillna(state_mode)
    print(f"  Filled remaining with state-wide mode: {state_mode}")
    print(f"  Final NaN: {sf['area_type'].isna().sum()}")

Before imputation:
  NaN area_type: 5360
  Constituencies with NaN: 42

After imputation:
area_type
Rur    42041
Urb    24629
Name: count, dtype: int64
  Remaining NaN: 0

In [23]:
sf.to_csv("stratification_frame_cleaned.csv", index=False)
print(f"Saved stratification_frame_cleaned.csv")
print(f"  Rows       : {len(sf):,}")
print(f"  Constituencies: {sf['constituency_name'].nunique()}")
print(f"  NaN area_type : {sf['area_type'].isna().sum()}")
print(f"  NaN gender    : {sf['gender'].isna().sum()}")

Saved stratification_frame_cleaned.csv
  Rows       : 66,670
  Constituencies: 294
  NaN area_type : 0
  NaN gender    : 0

In [22]:
candidates = pd.read_csv('west_bengal_candidates_2026.csv')
candidates.head()

,voting_date,district,constituency_no,constituency_name,AITC+_Party,AITC+_Candidate,NDA_Party,NDA_Candidate,LF+_Party,LF+_Candidate,INC_Party,INC_Candidate
0,23 April 2026,Cooch Behar,1,Mekliganj,Trinamool Congress,Paresh Adhikary,Bharatiya Janata Party,Dadhiram Roy,All India Forward Bloc,Kamal Roy,Indian National Congress,Ila Rani Roy
1,23 April 2026,Cooch Behar,2,Mathabhanga,Trinamool Congress,Sablu Barman,Bharatiya Janata Party,Nisith Pramanik,Communist Party of India (Marxist),Khagen Barman,Indian National Congress,Khitendra Nath Barman
2,23 April 2026,Cooch Behar,3,Cooch Behar Uttar,Trinamool Congress,Partha Pratim Roy,Bharatiya Janata Party,Sukumar Roy,Communist Party of India (Marxist),Pranay Karji,Indian National Congress,Partha Pratim Ishore
3,23 April 2026,Cooch Behar,4,Cooch Behar Dakshin,Trinamool Congress,Avijit Dey Bhowmik,Bharatiya Janata Party,Rathindra Nath Bose,All India Forward Bloc,Nazmul Alam Sarkar,Indian National Congress,Khokan Mian
4,23 April 2026,Cooch Behar,5,Sitalkuchi,Trinamool Congress,Harihar Das,Bharatiya Janata Party,Savitri Barman,Communist Party of India (Marxist),Nabadipti Adhikari,Indian National Congress,Sukamal Barman

In [23]:
results_2021 = pd.read_csv('wb_2021_results.csv')
results_2021.head()

,constituency,aitc_votes,aitc_pct,nda_votes,nda_pct,nota_votes,nota_pct,other_votes,other_pct
0,Alipurduars,91326.0,41.4,107333.0,48.6,1981,0.8,22092.0,10.0
1,Amdanga,88935.0,42.5,63455.0,30.3,2324,1.0,57028.0,27.3
2,Amta,102445.0,49.4,76240.0,36.7,1302,0.5,28823.0,14.0
3,Arambag,95936.0,44.3,103108.0,47.6,3171,1.3,17745.0,8.2
4,Asansol Dakshin,83394.0,43.6,87881.0,46.0,3466,1.3,19996.0,10.5

In [24]:
results_2024 = pd.read_csv('west_bengal_assembly_with_parliament_results.csv')
results_2024.head()

,constituency_name,parliament_seat_name,total_2021_electors,turnout,winner_party,winner_alliance,winner_candidate,winner_votes,winner_vote_pct,runnerup_party,runnerup_alliance,runnerup_candidate,runnerup_votes,runnerup_vote_pct,margin_votes,margin_pct
0,Mekliganj,Jalpaiguri,226465,83.66%,Bharatiya Janata Party,National Democratic Alliance,Jayanta Kumar Roy,766568,48.57,Trinamool Congress,Indian National Developmental Inclusive Alliance,Nirmal Chandra Roy,679875,43.07,|86693,|5.50
1,Mathabhanga,Cooch Behar,248022,82.16%,Trinamool Congress,Indian National Developmental Inclusive Alliance,Jagadish Basunia,788375,48.57,Bharatiya Janata Party,National Democratic Alliance,Nisith Pramanik,749125,46.16,|39250,|2.41
2,Cooch Behar Uttar,Cooch Behar,282988,82.16%,Trinamool Congress,Indian National Developmental Inclusive Alliance,Jagadish Basunia,788375,48.57,Bharatiya Janata Party,National Democratic Alliance,Nisith Pramanik,749125,46.16,|39250,|2.41
3,Cooch Behar Dakshin,Cooch Behar,233839,82.16%,Trinamool Congress,Indian National Developmental Inclusive Alliance,Jagadish Basunia,788375,48.57,Bharatiya Janata Party,National Democratic Alliance,Nisith Pramanik,749125,46.16,|39250,|2.41
4,Sitalkuchi,Cooch Behar,285260,82.16%,Trinamool Congress,Indian National Developmental Inclusive Alliance,Jagadish Basunia,788375,48.57,Bharatiya Janata Party,National Democratic Alliance,Nisith Pramanik,749125,46.16,|39250,|2.41

In [25]:
sf = pd.read_csv("stratification_frame_cleaned.csv")
sf.head()

,eroll_no,constituency_name,gender,age_band,area_type,R,G,SG,n_individuals,stratum_share
0,1.0,Mekliganj,Female,26-35,Rur,H,GEN,GUC,283,0.080880
1,1.0,Mekliganj,Male,36-45,Rur,H,GEN,GUC,274,0.078308
2,1.0,Mekliganj,Male,26-35,Rur,H,GEN,GUC,272,0.077736
3,1.0,Mekliganj,Female,36-45,Rur,H,GEN,GUC,244,0.069734
4,1.0,Mekliganj,Male,46-60,Rur,H,GEN,GUC,213,0.060875

In [26]:
merged = pd.read_csv("merged_sample_v1.csv")
merged.head()

,eroll_no,constituency_name,gender,age_band,area_type,R,G,SG,n_individuals,stratum_share,dup_count,will_vote,p_aitc,p_nda,p_lf,p_inc,p_nota,prob_sum
0,1.0,Mekliganj,Female,18-25,Rur,H,GEN,GUC,103,0.029437,6,True,0.48,0.49,0.0,0.0,0.03,1.0
1,1.0,Mekliganj,Female,18-25,Rur,H,GEN,GUC,103,0.029437,6,True,0.48,0.49,0.0,0.0,0.03,1.0
2,1.0,Mekliganj,Female,18-25,Rur,H,GEN,GUC,103,0.029437,6,True,0.48,0.49,0.0,0.0,0.03,1.0
3,1.0,Mekliganj,Female,18-25,Rur,H,GEN,GUC,103,0.029437,6,True,0.48,0.49,0.0,0.0,0.03,1.0
4,1.0,Mekliganj,Female,18-25,Rur,H,GEN,GUC,103,0.029437,6,True,0.48,0.49,0.0,0.0,0.03,1.0

In [27]:
import pandas as pd

candidates = pd.read_csv('west_bengal_candidates_2026.csv')
results_2021 = pd.read_csv('wb_2021_results.csv')
results_2024 = pd.read_csv('west_bengal_assembly_with_parliament_results.csv')
sf = pd.read_csv('stratification_frame_cleaned.csv')
merged = pd.read_csv('merged_sample_v1.csv')

sets = {
    'candidates': set(candidates['constituency_name'].str.strip().str.upper()),
    'results_2021': set(results_2021['constituency_name'].str.strip().str.upper()),
    'results_2024': set(results_2024['constituency_name'].str.strip().str.upper()),
    'sf': set(sf['constituency_name'].str.strip().str.upper()),
    'merged': set(merged['constituency_name'].str.strip().str.upper()),
}

for name, s in sets.items():
    print(f'{name}: {len(s)} constituencies')

common = set.intersection(*sets.values())
print(f'\nCommon across all 5: {len(common)}')

print('\n--- Extra in each df (not in common) ---')
for name, s in sets.items():
    extra = sorted(s - common)
    print(f'\n{name} ({len(extra)} extra):')
    for c in extra:
        print(f'  {c}')

candidates: 294 constituencies
results_2021: 294 constituencies
results_2024: 294 constituencies
sf: 294 constituencies
merged: 265 constituencies

Common across all 5: 265

--- Extra in each df (not in common) ---

candidates (29 extra):
  AUSGRAM
  BEHALA PASCHIM
  BEHALA PURBA
  BELEGHATA
  BHATAR
  BIDHANNAGAR
  BURDWAN UTTAR
  DARJEELING
  DURGAPUR PASCHIM
  DURGAPUR PURBA
  ENTALLY
  GALSI
  JORASANKO
  KALIMPONG
  KASBA
  KASHIPUR BELGACHHIA
  KATWA
  KETUGRAM
  KHARAGPUR SADAR
  KURSEONG
  MANGALKOT
  MANIKTOLA
  METIABURUZ
  PANDAVESWAR
  PURBASTHALI DAKSHIN
  PURBASTHALI UTTAR
  RAJARHAT NEW TOWN
  RASHBEHARI
  SHYAMPUKUR

results_2021 (29 extra):
  AUSGRAM
  BEHALA PASCHIM
  BEHALA PURBA
  BELEGHATA
  BHATAR
  BIDHANNAGAR
  BURDWAN UTTAR
  DARJEELING
  DURGAPUR PASCHIM
  DURGAPUR PURBA
  ENTALLY
  GALSI
  JORASANKO
  KALIMPONG
  KASBA
  KASHIPUR BELGACHHIA
  KATWA
  KETUGRAM
  KHARAGPUR SADAR
  KURSEONG
  MANGALKOT
  MANIKTOLA
  METIABURUZ
  PANDAVESWAR
  PURBASTHALI DAKSHIN
  PURBASTHALI UTTAR
  RAJARHAT NEW TOWN
  RASHBEHARI
  SHYAMPUKUR

results_2024 (29 extra):
  AUSGRAM
  BEHALA PASCHIM
  BEHALA PURBA
  BELEGHATA
  BHATAR
  BIDHANNAGAR
  BURDWAN UTTAR
  DARJEELING
  DURGAPUR PASCHIM
  DURGAPUR PURBA
  ENTALLY
  GALSI
  JORASANKO
  KALIMPONG
  KASBA
  KASHIPUR BELGACHHIA
  KATWA
  KETUGRAM
  KHARAGPUR SADAR
  KURSEONG
  MANGALKOT
  MANIKTOLA
  METIABURUZ
  PANDAVESWAR
  PURBASTHALI DAKSHIN
  PURBASTHALI UTTAR
  RAJARHAT NEW TOWN
  RASHBEHARI
  SHYAMPUKUR

sf (29 extra):
  AUSGRAM
  BEHALA PASCHIM
  BEHALA PURBA
  BELEGHATA
  BHATAR
  BIDHANNAGAR
  BURDWAN UTTAR
  DARJEELING
  DURGAPUR PASCHIM
  DURGAPUR PURBA
  ENTALLY
  GALSI
  JORASANKO
  KALIMPONG
  KASBA
  KASHIPUR BELGACHHIA
  KATWA
  KETUGRAM
  KHARAGPUR SADAR
  KURSEONG
  MANGALKOT
  MANIKTOLA
  METIABURUZ
  PANDAVESWAR
  PURBASTHALI DAKSHIN
  PURBASTHALI UTTAR
  RAJARHAT NEW TOWN
  RASHBEHARI
  SHYAMPUKUR

merged (0 extra):